### ISSUE TITLE
Ability to hide header

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/Jasonette#11]
Currently if you don't specify the body.header object, it just draws an empty opaque header at the top. 

But you may want to hide the header completely. Currently you can do this by setting the background to `rgba(0,0,0,0)` but it's an ad-hoc approach since the header is actually there but just not visible, which means you can't tap behind the header.

A better solution would be to just hide the header altogether. While this would not be difficult to implement, the problem is how to deal with navigation.

"If there's no navigation, how do you go back to the parent view?" was the question I've been asking. But I feel like this is something we could trust the developer to figure out. For example, the developer could add a floating button layer that has a `$back` action attached, etc.

Would anyone want this feature? If so, why?

**Comment by maks** [comment]
Im for implementing this.
Answer to nav is was, sometimes you might not want to have a back nav at all, eg. Games. User always has option of back button on Android and home button on iOS and Android.

**Comment by clsource** [comment]
I think the developer should have the option to hide the header (not just invisible) so the entire screen is able to trigger tap events.

So a complex navigation/design could use the header space.

Is up to the developer using this capability and design an alternative to the back button in iOS.

**Comment by gliechtenstein** [comment]
Resolved:

# iOS

![headernoheader](https://user-images.githubusercontent.com/16613330/30768950-d56c4206-9fc4-11e7-9d4d-2059c3c830b5.gif)

# Android

![headernoheaderandroid](https://user-images.githubusercontent.com/16613330/30768952-d95e3798-9fc4-11e7-8d92-a8fd5ca6ce37.gif)

**Comment by gliechtenstein** [comment]
The JSON used in the demo https://github.com/Jasonette/Jasonpedia/blob/gh-pages/view/header/index.json

**Comment by clsource** [comment]
Awesome Job! 👍 
You are great !
