### ISSUE TITLE
Switch bug

### ISSUE THREAD

**Issue by camillerimichael** [Jasonette/Jasonette#21]
Switch components seems to refuse parsing the value from either `"true" "false" "1" "0"`
Also, the action is not being triggered. I'm curious if anybody encountered such circumstances when using the switch in the templates

**Comment by clsource** [comment]
Hello, 
i kindly ask if you can write a json file with some sample code that
could be used for testing. So the error could be easily discovered and fixed :)

Thanks

**Comment by camillerimichael** [comment]
I'm using:
{
                          "type": "switch",
                          "value": "{{state}}",
                          "trigger": "changeState",
                          "action": {
                          "options": {
                            "item": "Light is On?"
                            }
                          }
                        }

Other data fields are populating properly in adjacent elements, however switch is always false and can't seem to find the data properly

**Comment by clsource** [comment]
it seems the "trigger" is not being used properly.
it should be inside the "action" 👍 
ex
```
"action": {
          "trigger": "banner",
          "options": {
            "item": "Light is On?"
          }
        }
```

**Comment by camillerimichael** [comment]
I tried that as well but the value was still not mirrored from the data set

**Comment by clsource** [comment]
What are the contents of the changeState function?

**Comment by camillerimichael** [comment]
For now change state displays a simple alert.

However my dataset has values for
"true", "false", true, false, "1", "0", 1, 0. None of them work and switch
just displays a switch in of state.

My data is an array of items having state as a property and I am rendering
a switch for each entry.

**Comment by camillerimichael** [comment]
I have tried the following to no avail:

`{
                          "type": "switch",
                          "value": "1",
                          "action": {
                          "trigger": "changeState",
                          "options": {
                            "item": "Light is On?"
                            }
                          }
                        }`

`{
                          "type": "switch",
                          "value": 1,
                          "action": {
                          "trigger": "changeState",
                          "options": {
                            "item": "Light is On?"
                            }
                          }
                        }`

**Comment by clsource** [comment]
which operating system are you trying this code on?
android, ios?

which version?

thanks

**Comment by camillerimichael** [comment]
I am testing on android 7

**Comment by clsource** [comment]
Here I created some simple switch jasons.

https://jasonbase.com/things/kgqL
https://jasonbase.com/things/mXqX

They worked properly in my iOS device.

Please try them in your device and report any issue :)

thanks.

**Comment by camillerimichael** [comment]
You're right they work fine. Go ahead and close the issue then, it is
surely something on my end. I will try to reproduce it or at least spot and
mistake I did and report back.

Thanks for your assistance :)

**Comment by clsource** [comment]
Glad to help 👍
