### ISSUE TITLE
iOS and Android optional properties for overwriting actions and styles 

### ISSUE THREAD

**Issue by clsource** [Jasonette/Jasonette#5]
Migrated from https://github.com/Jasonette/documentation/issues/83

Needed if you want a specific behaviour or style depending on the operating system. Inside each you could put an an object with an action and/or style that would overwrite the global action or style for the component.

```
{
"type" : "button",
"text" : "Click",
"style" : {
  "background" : "#3c3c3c",
  "color" : "#cccccc"
},
"options" : {
  "ios" : {
     "style" : {
       "background" : "#000000"
     }
   },
  "android" : {
     "style" : {
       "color" : "#ffffff"
    }
   }
 }
}
```

**Comment by clsource** [comment]
Maybe it could be done like this
```
{
 "{#ios}" : {
    ...
 },
"{#android}" : {
    ...
 }
```

**Comment by gliechtenstein** [comment]
You should be able to use the $env variables to do this: http://docs.jasonette.com/env/

```
{
  "type" : "button",
  "text" : "Click",
  "style" : {
    "background" : [{
      "{{#if $env.device.os.name === 'ios'}}": "#000000"
    }, {
      "{{#else}}": "#3c3c3c"
    }],
    "color" : [{
      "{{#if $env.device.os.name === 'ios'}}": "#cccccc"
    }, {
      "{{#else}}": "#ffffff"
    }]
  }
}]
```

or even shorter:

```
{
  "type" : "button",
  "text" : "Click",
  "style" : {
    "background": "{{$env.device.os.name === 'ios' ? '#000000' : '#3c3c3c'}}",
    "color": "{{$env.device.os.name === 'ios' ? '#cccccc' : '#ffffff'}}"
  }
}]
```

**Comment by clsource** [comment]
Sounds good. But what about a boolean that have that logic.
`{{$env.device.os.name === 'ios'}}`

Used like
`{{$env.device.os.android}}` and `{{$env.device.os.ios}}`

`"{{$env.device.os.name === 'ios' ? '#000000' : '#3c3c3c'}}"`

becomes

`"{{$env.device.os.ios ? '#000000' : '#3c3c3c'}}"`

:+1:

**Comment by gliechtenstein** [comment]
@clsource I am not sure if that's a good idea. These are environment variables, and most implementations of environment variables have the pattern of `key: value` where the key is a category and value is its value.

Allowing values as keys will make it hard to create a schema.

**Comment by clsource** [comment]
It´s a good point.
Besides if https://github.com/Jasonette/Jasonette/issues/4 will be implemented. A built in function could make this as convenience method.

I´m archiving this issue.

Thanks.
