### ISSUE TITLE
App build version as $env

### ISSUE THREAD

**Issue by gliechtenstein** [Jasonette/Jasonette#7]
It would be useful to have access to an `$env` variable for getting an app's build version.

This is available programmatically for both iOS and Android. As for the spec, I'm thinking

- `$env.app.versionCode` and `$env.app.versionName` for Android
- `$env.app.version` and `$env.app.build` for iOS

The variable names are different for ios and android to respect the original variable name for each platform respectively, but open for feedback.

**Comment by clsource** [comment]
I think this way it will be more explicit and cross platform friendly 👍 

```
$env.app.version.code
$env.app.version.name 
$env.app.version.build // same as $env.app.version.name
```

**Comment by maks** [comment]
Would be nice to have at least a cross-platform alias for both so that you could use the same env name withouth worrying about what platform you are on (sometimes you dont care which platform its running on).

**Comment by gliechtenstein** [comment]
Here's how versions work on ios and android:

- Android
  - versionName:  user-facing
  - versionCode: internal
- iOS
  - version: user-facing
  - build: internal


I agree with @maks that it would be convenient to have a cross platform way of referring to these.

So based on the facts above, how about:

-`$env.app.version.internal`: versionCode (android), build (ios) 
-`$env.app.version.external`: versionName (android), version (ios)

Or if you have better suggestions please do share.

**Comment by clsource** [comment]
I think that's nicer.

How about this.

```
$env.app.version.public // external
$env.app.version.private // internal
```

**Comment by ghost** [comment]
I think this got too complicated. For Android the versionName (as far as I know) is just a display name, nothing meaningful about it, I would prefer that there just be:

$env.app.build <--- versionCode for Android, and Identity build for iOS

**Comment by clsource** [comment]
@darenr  so It will follow what iOS have?

```
$env.app.version // versionName for Android and Version for iOS
$env.app.build // versionCode for Android and Build for iOS
```

**Comment by ghost** [comment]
version and build are generic enough that I don't think any one using android would get confused, it's just the source of these values is different for each platform. Jasonette is abstraction the idea behind these terms.

**Comment by clsource** [comment]
@darenr you are right, I'm ok with that.

**Comment by gliechtenstein** [comment]
Resolved.
